from enum import StrEnum


class UserRoleName(StrEnum):
    USER = "USER"
    CONTRIBUTOR = "CONTRIBUTOR"
    LINGUIST_REVIEWER = "LINGUIST_REVIEWER"
    ML_REVIEWER = "ML_REVIEWER"
    ADMIN = "ADMIN"


class SignStatus(StrEnum):
    DRAFT = "DRAFT"
    EXPERIMENTAL = "EXPERIMENTAL"
    ACTIVE = "ACTIVE"
    DEPRECATED = "DEPRECATED"


class RiskLevel(StrEnum):
    NORMAL = "NORMAL"
    SENSITIVE = "SENSITIVE"
    MEDICAL = "MEDICAL"
    LEGAL = "LEGAL"
    FINANCIAL = "FINANCIAL"
    EMERGENCY = "EMERGENCY"


class ModelStatus(StrEnum):
    DRAFT = "DRAFT"
    TRAINING = "TRAINING"
    EVALUATING = "EVALUATING"
    VALIDATING = "VALIDATING"
    VALIDATED_SMOKE = "VALIDATED_SMOKE"
    READY = "READY"
    REJECTED = "REJECTED"
    ACTIVE = "ACTIVE"
    ARCHIVED = "ARCHIVED"
    FAILED = "FAILED"


class RecognitionTaskType(StrEnum):
    ALPHABET_STATIC = "ALPHABET_STATIC"
    WORD_ISOLATED = "WORD_ISOLATED"
    CONTINUOUS_SIGNING = "CONTINUOUS_SIGNING"


class InputModality(StrEnum):
    LANDMARK_SEQUENCE = "LANDMARK_SEQUENCE"
    IMAGE = "IMAGE"
    VIDEO = "VIDEO"


class ExternalDatasetProvider(StrEnum):
    KAGGLE = "kaggle"
    MENDELEY = "mendeley"
    DOCUMENTATION = "documentation"


class ExternalDatasetLicenseStatus(StrEnum):
    VERIFIED = "VERIFIED"
    TO_VERIFY = "TO_VERIFY"
    INCOMPATIBLE = "INCOMPATIBLE"
    UNKNOWN = "UNKNOWN"


class ExternalDatasetSourceStatus(StrEnum):
    REGISTERED = "REGISTERED"
    LICENSE_PENDING = "LICENSE_PENDING"
    DOWNLOAD_READY = "DOWNLOAD_READY"
    DOWNLOADING = "DOWNLOADING"
    DOWNLOADED = "DOWNLOADED"
    AUDITING = "AUDITING"
    AUDIT_FAILED = "AUDIT_FAILED"
    REQUIRES_REVIEW = "REQUIRES_REVIEW"
    VALIDATED = "VALIDATED"
    PREPROCESSING = "PREPROCESSING"
    READY = "READY"
    DISABLED = "DISABLED"
    REJECTED = "REJECTED"


class ExternalDatasetLabelStatus(StrEnum):
    UNMAPPED = "UNMAPPED"
    AUTOMATIC_SUGGESTION = "AUTOMATIC_SUGGESTION"
    PENDING_REVIEW = "PENDING_REVIEW"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    AMBIGUOUS = "AMBIGUOUS"
    DUPLICATE = "DUPLICATE"


class RecognitionStatus(StrEnum):
    CREATED = "CREATED"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    UNCERTAIN = "UNCERTAIN"
    FAILED = "FAILED"


class RecognitionDecision(StrEnum):
    KNOWN = "known"
    UNCERTAIN = "uncertain"
    UNKNOWN = "unknown"


class ConfidenceLevel(StrEnum):
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"


class CorrectionType(StrEnum):
    CONFIRMED_TOP_1 = "CONFIRMED_TOP_1"
    SELECTED_ALTERNATIVE = "SELECTED_ALTERNATIVE"
    SELECTED_OTHER_SIGN = "SELECTED_OTHER_SIGN"
    MARKED_UNKNOWN = "MARKED_UNKNOWN"
    MANUAL_TEXT = "MANUAL_TEXT"


class DominantHand(StrEnum):
    LEFT = "LEFT"
    RIGHT = "RIGHT"
    AMBIDEXTROUS = "AMBIDEXTROUS"
    UNDISCLOSED = "UNDISCLOSED"


class SigningExperienceLevel(StrEnum):
    NATIVE_SIGNER = "NATIVE_SIGNER"
    FLUENT_SIGNER = "FLUENT_SIGNER"
    LEARNER = "LEARNER"
    INTERPRETER = "INTERPRETER"
    UNDISCLOSED = "UNDISCLOSED"


class ConsentType(StrEnum):
    LANDMARK_PROCESSING = "LANDMARK_PROCESSING"
    LANDMARK_STORAGE = "LANDMARK_STORAGE"
    VIDEO_RECORDING = "VIDEO_RECORDING"
    VIDEO_STORAGE = "VIDEO_STORAGE"
    RESEARCH_USE = "RESEARCH_USE"
    MODEL_TRAINING = "MODEL_TRAINING"
    PUBLIC_DATASET_RELEASE = "PUBLIC_DATASET_RELEASE"
    COMMERCIAL_USE = "COMMERCIAL_USE"
    CONTACT_FOR_FUTURE_STUDIES = "CONTACT_FOR_FUTURE_STUDIES"


class CampaignStatus(StrEnum):
    DRAFT = "DRAFT"
    SCHEDULED = "SCHEDULED"
    ACTIVE = "ACTIVE"
    PAUSED = "PAUSED"
    COMPLETED = "COMPLETED"
    ARCHIVED = "ARCHIVED"


class ContributionStatus(StrEnum):
    DRAFT = "DRAFT"
    CAPTURING = "CAPTURING"
    READY_TO_SUBMIT = "READY_TO_SUBMIT"
    UPLOADING = "UPLOADING"
    SUBMITTED = "SUBMITTED"
    AUTOMATIC_CHECK_FAILED = "AUTOMATIC_CHECK_FAILED"
    PENDING_LINGUIST_REVIEW = "PENDING_LINGUIST_REVIEW"
    LINGUIST_REJECTED = "LINGUIST_REJECTED"
    PENDING_ML_REVIEW = "PENDING_ML_REVIEW"
    ML_REJECTED = "ML_REJECTED"
    APPROVED = "APPROVED"
    REVISION_REQUESTED = "REVISION_REQUESTED"
    REVOKED = "REVOKED"
    ARCHIVED = "ARCHIVED"


class AutomaticQualityStatus(StrEnum):
    PASSED = "PASSED"
    WARNING = "WARNING"
    FAILED = "FAILED"


class ReviewType(StrEnum):
    LINGUISTIC = "LINGUISTIC"
    TECHNICAL = "TECHNICAL"
    PRIVACY = "PRIVACY"
    ADMINISTRATIVE = "ADMINISTRATIVE"


class ReviewDecision(StrEnum):
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    REVISION_REQUESTED = "REVISION_REQUESTED"
    FLAGGED = "FLAGGED"


class DatasetVersionStatus(StrEnum):
    DRAFT = "DRAFT"
    BUILDING = "BUILDING"
    VALIDATING = "VALIDATING"
    READY = "READY"
    PUBLISHED = "PUBLISHED"
    FAILED = "FAILED"
    ARCHIVED = "ARCHIVED"


class DatasetSplit(StrEnum):
    TRAIN = "TRAIN"
    VALIDATION = "VALIDATION"
    TEST = "TEST"
    HOLDOUT = "HOLDOUT"


class SemanticConceptType(StrEnum):
    PRONOUN = "PRONOUN"
    ACTION = "ACTION"
    OBJECT = "OBJECT"
    LOCATION = "LOCATION"
    QUESTION = "QUESTION"
    NEGATION = "NEGATION"
    AFFIRMATION = "AFFIRMATION"
    POLITENESS = "POLITENESS"
    TIME = "TIME"
    QUANTITY = "QUANTITY"
    HEALTH = "HEALTH"
    EMERGENCY = "EMERGENCY"
    PERSON = "PERSON"
    PUNCTUATION = "PUNCTUATION"
    OTHER = "OTHER"


class LinguisticLanguage(StrEnum):
    DARIJA = "DARIJA"
    FRENCH = "FRENCH"
    ENGLISH = "ENGLISH"


class LinguisticScript(StrEnum):
    ARABIC = "ARABIC"
    LATIN = "LATIN"
    LATIN_ARABIZI = "LATIN_ARABIZI"


class LinguisticRegister(StrEnum):
    NEUTRAL = "NEUTRAL"
    POLITE = "POLITE"
    INFORMAL = "INFORMAL"
    FORMAL = "FORMAL"
    MEDICAL = "MEDICAL"
    EMERGENCY = "EMERGENCY"


class LinguisticAssetStatus(StrEnum):
    DRAFT = "DRAFT"
    VALIDATING = "VALIDATING"
    ACTIVE = "ACTIVE"
    DEPRECATED = "DEPRECATED"


class MessageStatus(StrEnum):
    DRAFT = "DRAFT"
    GENERATING = "GENERATING"
    READY = "READY"
    COMPLETED = "COMPLETED"
    ARCHIVED = "ARCHIVED"
    DELETED = "DELETED"


class MessageItemType(StrEnum):
    CONFIRMED_SIGN = "CONFIRMED_SIGN"
    MANUAL_WORD = "MANUAL_WORD"
    FINGERSPELLED_LETTER = "FINGERSPELLED_LETTER"
    FINGERSPELLED_WORD = "FINGERSPELLED_WORD"
    PUNCTUATION = "PUNCTUATION"
    TEMPLATE_ELEMENT = "TEMPLATE_ELEMENT"
    SYSTEM_INSERTED = "SYSTEM_INSERTED"


class MessageItemSource(StrEnum):
    RECOGNITION_TOP_1 = "RECOGNITION_TOP_1"
    RECOGNITION_ALTERNATIVE = "RECOGNITION_ALTERNATIVE"
    FINGERSPELLING = "FINGERSPELLING"
    USER_CORRECTION = "USER_CORRECTION"
    MANUAL_INPUT = "MANUAL_INPUT"
    LINGUISTIC_RULE = "LINGUISTIC_RULE"
    TEMPLATE = "TEMPLATE"


class MessageRevisionChangeType(StrEnum):
    ITEM_ADDED = "ITEM_ADDED"
    ITEM_REMOVED = "ITEM_REMOVED"
    ITEM_MOVED = "ITEM_MOVED"
    ITEM_REPLACED = "ITEM_REPLACED"
    TEXT_EDITED = "TEXT_EDITED"
    GENERATED = "GENERATED"
    REGENERATED = "REGENERATED"
    RESTORED = "RESTORED"
    FINALIZED = "FINALIZED"


class SpeechGenerationStatus(StrEnum):
    CREATED = "CREATED"
    QUEUED = "QUEUED"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    EXPIRED = "EXPIRED"
    DELETED = "DELETED"


class LinguisticStatus(StrEnum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    INCOMPLETE = "INCOMPLETE"
    AMBIGUOUS = "AMBIGUOUS"
