from enum import StrEnum


class UserRoleName(StrEnum):
    USER = "USER"
    CONTRIBUTOR = "CONTRIBUTOR"
    LINGUIST_REVIEWER = "LINGUIST_REVIEWER"
    ML_REVIEWER = "ML_REVIEWER"
    ADMIN = "ADMIN"


class SignStatus(StrEnum):
    DRAFT = "DRAFT"
    EXPERIMENTAL = "EXPERIMENTAL"
    ACTIVE = "ACTIVE"
    DEPRECATED = "DEPRECATED"


class RiskLevel(StrEnum):
    NORMAL = "NORMAL"
    SENSITIVE = "SENSITIVE"
    MEDICAL = "MEDICAL"
    LEGAL = "LEGAL"
    FINANCIAL = "FINANCIAL"
    EMERGENCY = "EMERGENCY"


class ModelStatus(StrEnum):
    DRAFT = "DRAFT"
    TRAINING = "TRAINING"
    EVALUATING = "EVALUATING"
    VALIDATING = "VALIDATING"
    READY = "READY"
    REJECTED = "REJECTED"
    ACTIVE = "ACTIVE"
    ARCHIVED = "ARCHIVED"
    FAILED = "FAILED"


class RecognitionStatus(StrEnum):
    CREATED = "CREATED"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    UNCERTAIN = "UNCERTAIN"
    FAILED = "FAILED"


class RecognitionDecision(StrEnum):
    KNOWN = "known"
    UNCERTAIN = "uncertain"
    UNKNOWN = "unknown"


class ConfidenceLevel(StrEnum):
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"


class CorrectionType(StrEnum):
    CONFIRMED_TOP_1 = "CONFIRMED_TOP_1"
    SELECTED_ALTERNATIVE = "SELECTED_ALTERNATIVE"
    SELECTED_OTHER_SIGN = "SELECTED_OTHER_SIGN"
    MARKED_UNKNOWN = "MARKED_UNKNOWN"
    MANUAL_TEXT = "MANUAL_TEXT"


class DominantHand(StrEnum):
    LEFT = "LEFT"
    RIGHT = "RIGHT"
    AMBIDEXTROUS = "AMBIDEXTROUS"
    UNDISCLOSED = "UNDISCLOSED"


class SigningExperienceLevel(StrEnum):
    NATIVE_SIGNER = "NATIVE_SIGNER"
    FLUENT_SIGNER = "FLUENT_SIGNER"
    LEARNER = "LEARNER"
    INTERPRETER = "INTERPRETER"
    UNDISCLOSED = "UNDISCLOSED"


class ConsentType(StrEnum):
    LANDMARK_PROCESSING = "LANDMARK_PROCESSING"
    LANDMARK_STORAGE = "LANDMARK_STORAGE"
    VIDEO_RECORDING = "VIDEO_RECORDING"
    VIDEO_STORAGE = "VIDEO_STORAGE"
    RESEARCH_USE = "RESEARCH_USE"
    MODEL_TRAINING = "MODEL_TRAINING"
    PUBLIC_DATASET_RELEASE = "PUBLIC_DATASET_RELEASE"
    COMMERCIAL_USE = "COMMERCIAL_USE"
    CONTACT_FOR_FUTURE_STUDIES = "CONTACT_FOR_FUTURE_STUDIES"


class CampaignStatus(StrEnum):
    DRAFT = "DRAFT"
    SCHEDULED = "SCHEDULED"
    ACTIVE = "ACTIVE"
    PAUSED = "PAUSED"
    COMPLETED = "COMPLETED"
    ARCHIVED = "ARCHIVED"


class ContributionStatus(StrEnum):
    DRAFT = "DRAFT"
    CAPTURING = "CAPTURING"
    READY_TO_SUBMIT = "READY_TO_SUBMIT"
    UPLOADING = "UPLOADING"
    SUBMITTED = "SUBMITTED"
    AUTOMATIC_CHECK_FAILED = "AUTOMATIC_CHECK_FAILED"
    PENDING_LINGUIST_REVIEW = "PENDING_LINGUIST_REVIEW"
    LINGUIST_REJECTED = "LINGUIST_REJECTED"
    PENDING_ML_REVIEW = "PENDING_ML_REVIEW"
    ML_REJECTED = "ML_REJECTED"
    APPROVED = "APPROVED"
    REVISION_REQUESTED = "REVISION_REQUESTED"
    REVOKED = "REVOKED"
    ARCHIVED = "ARCHIVED"


class AutomaticQualityStatus(StrEnum):
    PASSED = "PASSED"
    WARNING = "WARNING"
    FAILED = "FAILED"


class ReviewType(StrEnum):
    LINGUISTIC = "LINGUISTIC"
    TECHNICAL = "TECHNICAL"
    PRIVACY = "PRIVACY"
    ADMINISTRATIVE = "ADMINISTRATIVE"


class ReviewDecision(StrEnum):
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    REVISION_REQUESTED = "REVISION_REQUESTED"
    FLAGGED = "FLAGGED"


class DatasetVersionStatus(StrEnum):
    DRAFT = "DRAFT"
    BUILDING = "BUILDING"
    VALIDATING = "VALIDATING"
    READY = "READY"
    PUBLISHED = "PUBLISHED"
    FAILED = "FAILED"
    ARCHIVED = "ARCHIVED"


class DatasetSplit(StrEnum):
    TRAIN = "TRAIN"
    VALIDATION = "VALIDATION"
    TEST = "TEST"
    HOLDOUT = "HOLDOUT"
