export type CameraStatus =
  | 'IDLE'
  | 'REQUESTING_PERMISSION'
  | 'PERMISSION_GRANTED'
  | 'PERMISSION_DENIED'
  | 'READY'
  | 'STOPPED'
  | 'ERROR'
  | 'UNSUPPORTED';

export type CameraErrorCode =
  | 'UNSUPPORTED'
  | 'INSECURE_CONTEXT'
  | 'PERMISSION_DENIED'
  | 'NOT_FOUND'
  | 'IN_USE'
  | 'CONSTRAINT_NOT_SUPPORTED'
  | 'INTERRUPTED'
  | 'SYSTEM_ERROR';
